import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/src/components/ui/sonner";
import { BottomNavigationBar } from "@/src/components/layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "다모",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}
      >
        <div className="flex min-h-[100dvh] flex-col">
        {/* 스크롤 영역 */}
        <main className="flex-1 overflow-y-auto pb-8">
            {children}
        </main>

        {/* 고정 하단 네비 */}
        <BottomNavigationBar />
        </div>
        <Toaster />
      </body>
    </html>
  );
}
